import type { Family, Level } from './types';
import { difficultyForLevel } from './difficulty';

// Corpus original français : familles concrètes, culture générale et notions du quotidien.
// Les niveaux sont dérivés localement et déterministement de ce corpus, sans réseau.
const SEEDS: Array<[string, string, string, string, string]> = [
  ['Animaux domestiques','chat','chien','lapin','hamster'],
  ['Animaux de la ferme','vache','cochon','mouton','poule'],
  ['Animaux de la forêt','cerf','renard','blaireau','écureuil'],
  ['Animaux de la savane','lion','zèbre','girafe','éléphant'],
  ['Animaux polaires','ours blanc','phoque','morse','manchot'],
  ['Animaux marins','dauphin','baleine','requin','pieuvre'],
  ['Oiseaux communs','moineau','merle','hirondelle','corbeau'],
  ['Oiseaux de proie','aigle','faucon','hibou','buse'],
  ['Insectes','abeille','fourmi','papillon','coccinelle'],
  ['Reptiles','lézard','serpent','tortue','crocodile'],
  ['Fruits rouges','fraise','framboise','groseille','cerise'],
  ['Fruits exotiques','mangue','ananas','papaye','kiwi'],
  ['Agrumes','orange','citron','pamplemousse','clémentine'],
  ['Fruits à noyau','pêche','abricot','prune','nectarine'],
  ['Légumes-racines','carotte','navet','radis','betterave'],
  ['Légumes verts','épinard','brocoli','courgette','haricot vert'],
  ['Champignons','cèpe','girolle','morille','pleurote'],
  ['Herbes aromatiques','basilic','thym','romarin','ciboulette'],
  ['Épices','cannelle','curcuma','paprika','gingembre'],
  ['Pâtisseries','éclair','tarte','macaron','mille-feuille'],
  ['Pains','baguette','brioche','seigle','pain complet'],
  ['Fromages français','camembert','comté','roquefort','reblochon'],
  ['Boissons chaudes','café','thé','chocolat chaud','infusion'],
  ['Plats italiens','pizza','risotto','lasagnes','raviolis'],
  ['Plats asiatiques','sushi','ramen','curry','nems'],
  ['Plats méditerranéens','couscous','paella','moussaka','taboulé'],
  ['Instruments à cordes','guitare','violon','harpe','contrebasse'],
  ['Instruments à vent','flûte','clarinette','trompette','saxophone'],
  ['Percussions','batterie','xylophone','tambour','cajón'],
  ['Styles musicaux','jazz','rock','reggae','classique'],
  ['Danses','valse','tango','salsa','hip-hop'],
  ['Sports de ballon','football','basket-ball','volley-ball','handball'],
  ['Sports de raquette','tennis','badminton','squash','ping-pong'],
  ['Sports nautiques','voile','surf','aviron','plongée'],
  ['Sports d’hiver','ski','snowboard','luge','curling'],
  ['Athlétisme','sprint','marathon','relais','saut en hauteur'],
  ['Arts martiaux','judo','karaté','aïkido','taekwondo'],
  ['Randonnée','sac à dos','boussole','gourde','bâtons'],
  ['Météo','pluie','neige','orage','brouillard'],
  ['Phénomènes célestes','éclipse','comète','aurore','météorite'],
  ['Planètes','Mercure','Vénus','Mars','Jupiter'],
  ['Constellations','Orion','Cassiopée','Andromède','Grande Ourse'],
  ['Pays nordiques','Norvège','Suède','Finlande','Islande'],
  ['Capitales européennes','Paris','Rome','Lisbonne','Vienne'],
  ['Villes françaises','Lyon','Nantes','Toulouse','Strasbourg'],
  ['Reliefs','montagne','colline','plateau','vallée'],
  ['Milieux aquatiques','lac','rivière','marais','cascade'],
  ['Littoral','plage','falaise','dune','estuaire'],
  ['Matériel scolaire','cahier','trousse','règle','cartable'],
  ['Bureau','agrafeuse','tampon','classeur','enveloppe'],
  ['Meubles','table','chaise','armoire','étagère'],
  ['Pièces de la maison','cuisine','salon','grenier','cave'],
  ['Salle de bains','savon','serviette','miroir','brosse à dents'],
  ['Ustensiles de cuisine','fouet','passoire','spatule','casserole'],
  ['Appareils ménagers','four','grille-pain','aspirateur','réfrigérateur'],
  ['Bricolage','marteau','tournevis','scie','niveau à bulle'],
  ['Matériaux','bois','verre','acier','béton'],
  ['Vêtements','pantalon','chemise','pull','chaussettes'],
  ['Vêtements d’extérieur','manteau','imperméable','écharpe','gants'],
  ['Chaussures','baskets','bottes','sandales','mocassins'],
  ['Accessoires','ceinture','chapeau','foulard','montre'],
  ['Couleurs chaudes','rouge','orange','jaune','ocre'],
  ['Couleurs froides','bleu','vert','violet','turquoise'],
  ['Couleurs neutres','blanc','noir','gris','beige'],
  ['Formes géométriques','cercle','carré','triangle','hexagone'],
  ['Matières textiles','coton','laine','soie','lin'],
  ['Transports','train','bus','avion','bateau'],
  ['Véhicules routiers','voiture','camion','moto','autocar'],
  ['Deux-roues','vélo','scooter','trottinette','mobylette'],
  ['Éléments de la route','trottoir','carrefour','rond-point','passage piéton'],
  ['Métiers de la santé','médecin','infirmier','dentiste','pharmacien'],
  ['Métiers de l’éducation','enseignant','professeur','bibliothécaire','éducateur'],
  ['Métiers de la création','peintre','scénariste','photographe','designer'],
  ['Métiers du bâtiment','maçon','plombier','électricien','charpentier'],
  ['Métiers de la mer','marin','pêcheur','capitaine','plongeur'],
  ['Métiers de la cuisine','chef','pâtissier','boulanger','serveur'],
  ['Outils numériques','clavier','souris','écran','imprimante'],
  ['Photographie','objectif','trépied','flash','portrait'],
  ['Cinéma','caméra','acteur','réalisateur','montage'],
  ['Théâtre','scène','rideau','réplique','costume'],
  ['Littérature','roman','poésie','nouvelle','essai'],
  ['Genres de fiction','aventure','policier','fantastique','science-fiction'],
  ['Presse','article','titre','éditorial','reportage'],
  ['Jeux de société','échecs','dominos','puzzle','dames'],
  ['Jeux de cartes','belote','tarot','bridge','solitaire'],
  ['Activités créatives','dessin','peinture','tricot','modelage'],
  ['Loisirs de plein air','pique-nique','camping','jardinage','observation'],
  ['Vacances','valise','hôtel','itinéraire','souvenir'],
  ['Objets de voyage','passeport','billet','guide','étiquette'],
  ['Fêtes','anniversaire','mariage','carnaval','réveillon'],
  ['Décorations','guirlande','bougie','confetti','lanterne'],
  ['Émotions positives','joie','fierté','espoir','sérénité'],
  ['Émotions nuancées','nostalgie','surprise','doute','mélancolie'],
  ['Qualités humaines','patience','courage','curiosité','générosité'],
  ['Relations sociales','ami','voisin','collègue','famille'],
  ['Communication','conversation','message','écoute','geste'],
  ['Temps et calendrier','semaine','mois','saison','siècle'],
  ['Moments de la journée','aube','matin','midi','crépuscule'],
  ['Unités de mesure','mètre','litre','gramme','seconde'],
  ['Sciences physiques','force','énergie','lumière','chaleur'],
  ['Chimie','atome','molécule','acide','cristal'],
  ['Biologie','cellule','gène','organe','tissu'],
  ['Anatomie','cœur','poumon','foie','cerveau'],
  ['Santé quotidienne','sommeil','hydratation','repos','respiration'],
  ['Jardinage','graine','terreau','arrosoir','sécateur'],
  ['Arbres','chêne','érable','sapin','olivier'],
  ['Fleurs','rose','tulipe','iris','coquelicot'],
  ['Plantes aromatiques','menthe','sauge','estragon','laurier'],
  ['Écologie','recyclage','compost','biodiversité','énergie solaire'],
  ['Minéraux','quartz','marbre','granit','ardoise'],
  ['Métaux','or','argent','cuivre','aluminium'],
  ['Architecture','façade','toit','colonne','balcon'],
  ['Monuments','pont','tour','château','phare'],
  ['Histoire','empire','révolution','dynastie','traité'],
  ['Antiquité','temple','forum','pyramide','gladiateur'],
  ['Moyen Âge','chevalier','donjon','blason','marché'],
  ['Renaissance','atelier','perspective','imprimerie','mécène'],
  ['Sciences humaines','société','culture','langue','mémoire'],
  ['Citoyenneté','loi','vote','justice','droit'],
  ['Économie','budget','épargne','marché','salaire'],
  ['Commerce','boutique','client','facture','livraison'],
  ['Banque','compte','carte','virement','crédit'],
  ['Langues','mot','verbe','accent','traduction'],
  ['Grammaire','nom','adjectif','pronom','conjonction'],
  ['Typographie','lettre','espace','ponctuation','paragraphe'],
  ['Orientation','nord','sud','est','ouest'],
  ['Cartographie','carte','légende','échelle','coordonnées'],
  ['Camping','tente','réchaud','sac de couchage','lampe frontale'],
  ['Mer et navigation','marée','courant','écume','bouée'],
  ['Montagne','sommet','refuge','sentier','glacier'],
  ['Forêt','sous-bois','mousse','clairière','fougère'],
  ['Désert','oasis','dune','caravane','cactus'],
  ['Paysages','prairie','verger','vignoble','rizière'],
  ['Sons','bruit','silence','écho','mélodie'],
  ['Textures','lisse','rugueux','doux','granuleux'],
  ['Lumières','ombre','reflet','éclat','halo'],
  ['Parfums','vanille','lavande','cèdre','agrumes'],
  ['Goûts','sucré','salé','amer','acidulé'],
  ['Actions manuelles','plier','couper','visser','nouer'],
  ['Déplacements','marcher','courir','sauter','glisser'],
  ['Verbes de parole','dire','raconter','répondre','chuchoter'],
  ['Verbes de pensée','imaginer','comprendre','douter','décider'],
  ['Adjectifs de taille','petit','grand','minuscule','immense'],
  ['Adjectifs de vitesse','lent','rapide','vif','paisible'],
  ['Objets ronds','balle','assiette','roue','bague'],
  ['Objets pointus','aiguille','clou','crayon','compas'],
  ['Objets pliables','parapluie','carte','éventail','accordéon'],
  ['Objets transparents','vitre','bocal','lunettes','glaçon'],
  ['Objets lumineux','lampe','bougie','étoile','écran'],
  ['Objets de poche','clé','pièce','mouchoir','briquet'],
  ['Symboles','étoile','cœur','flèche','éclair'],
  ['Paires opposées','chaud','froid','haut','bas'],
  ['Notions spatiales','devant','derrière','dessus','dessous'],
  ['Notions temporelles','avant','après','pendant','jamais'],
  ['Cuisine française','quiche','crêpe','ratatouille','gratin'],
  ['Sauces','pesto','béchamel','vinaigrette','coulis'],
  ['Desserts','mousse','crème','sorbet','compote'],
  ['Céréales','blé','riz','avoine','maïs'],
  ['Légumineuses','haricot','lentille','pois','fève'],
  ['Noix et graines','noisette','amande','noix','pistache'],
  ['Vocabulaire du voyage','départ','arrivée','escale','bagage'],
  ['Vocabulaire de la ville','rue','place','quartier','mairie'],
  ['Vocabulaire de la maison','porte','fenêtre','mur','plancher'],
  ['Vocabulaire du travail','réunion','projet','pause','objectif'],
  ['Vocabulaire de la lecture','page','chapitre','marque-page','couverture'],
  ['Vocabulaire de la musique','tempo','accord','rythme','refrain'],
  ['Vocabulaire du sport','équipe','arbitre','score','terrain'],
  ['Vocabulaire de la nature','terre','eau','air','feu'],
  ['Vocabulaire de l’espace','fusée','orbite','astronaute','satellite'],
  ['Vocabulaire du laboratoire','éprouvette','microscope','blouse','pipette'],
  ['Vocabulaire de la sécurité','alarme','casque','gilet','trousse de secours'],
  ['Vocabulaire de l’entretien','balai','seau','éponge','lessive'],
  ['Vocabulaire de la réparation','pièce détachée','clé plate','ruban','graisse'],
  ['Vocabulaire du textile','aiguille','fil','bouton','ourlet'],
  ['Vocabulaire de la peinture','pinceau','palette','toile','pigment'],
  ['Vocabulaire de la sculpture','argile','burin','socle','statue'],
  ['Vocabulaire de la danse','pas','rythme','costume','chorégraphie'],
  ['Vocabulaire de la scène','projecteur','coulisse','loges','décor'],
  ['Vocabulaire de la mer','ancre','gouvernail','proue','cabine'],
  ['Vocabulaire des oiseaux','plume','nid','aile','bec'],
  ['Vocabulaire des mammifères','fourrure','museau','patte','portée'],
  ['Vocabulaire des arbres','écorce','branche','racine','feuille'],
  ['Vocabulaire des fleurs','pétale','tige','pollen','bouquet'],
  ['Vocabulaire des fruits','peau','chair','pépin','jus'],
  ['Vocabulaire du pain','farine','levure','croûte','mie'],
  ['Vocabulaire du fromage','lait','meule','croûte','affinage'],
  ['Vocabulaire du chocolat','cacao','tablette','praliné','ganache'],
  ['Vocabulaire du café','grain','mouture','tasse','arôme'],
  ['Vocabulaire du thé','feuille','infusion','théière','tasse'],
  ['Vocabulaire du petit déjeuner','tartine','confiture','céréales','yaourt'],
  ['Vocabulaire du repas','entrée','plat','dessert','menu'],
  ['Vocabulaire des vêtements','manche','col','poche','fermeture'],
  ['Vocabulaire des chaussures','semelle','lacets','talon','pointure'],
  ['Vocabulaire de l’hiver','givre','écharpe','cheminée','moufles'],
  ['Vocabulaire de l’été','soleil','glace','vacances','ventilateur'],
  ['Vocabulaire du printemps','bourgeon','averse','hirondelle','floraison'],
  ['Vocabulaire de l’automne','feuille morte','châtaigne','brume','récolte'],
  ['Vocabulaire de la nuit','lune','veilleuse','rêve','étoile'],
  ['Vocabulaire du matin','réveil','brosse','café','agenda'],
  ['Vocabulaire de la détente','sieste','lecture','musique','promenade'],
  ['Vocabulaire de la réussite','effort','progrès','objectif','récompense'],
  ['Vocabulaire de la réflexion','question','indice','hypothèse','solution'],
  ['Vocabulaire de la mémoire','souvenir','repère','rappel','association'],
  ['Vocabulaire de l’organisation','liste','planning','dossier','priorité'],
  ['Vocabulaire de la découverte','curiosité','carte','expérience','surprise'],
  ['Vocabulaire de la coopération','équipe','partage','entraide','confiance'],
  ['Vocabulaire de la créativité','idée','esquisse','inspiration','invention'],
  ['Vocabulaire de la précision','mesure','détail','repère','contrôle'],
  ['Vocabulaire de la patience','attente','calme','constance','persévérance'],
  ['Vocabulaire du mouvement','élan','tour','équilibre','trajectoire'],
  ['Vocabulaire des couleurs','teinte','nuance','palette','contraste'],
  ['Vocabulaire des formes','ligne','courbe','angle','volume'],
  ['Vocabulaire des matières','bois','pierre','métal','tissu'],
  ['Vocabulaire des saisons','hiver','printemps','été','automne'],
  ['Vocabulaire de la technologie','capteur','batterie','réseau','algorithme'],
  ['Vocabulaire du numérique','fichier','dossier','fenêtre','curseur'],
  ['Vocabulaire de l’information','source','donnée','preuve','contexte'],
  ['Vocabulaire de la décision','choix','raison','option','conséquence'],
  ['Vocabulaire de la gestion','ressource','coût','gain','équilibre'],
  ['Vocabulaire de la famille','parent','enfant','frère','sœur'],
  ['Vocabulaire du quotidien','clé','sac','téléphone','agenda'],
  ['Vocabulaire de la santé','symptôme','soin','conseil','guérison'],
  ['Vocabulaire du corps','main','pied','visage','épaule'],
  ['Vocabulaire des sens','vue','ouïe','odorat','goût'],
  ['Vocabulaire des poissons','nageoire','écaille','banc','aquarium'],
  ['Vocabulaire des volcans','cratère','lave','cendre','éruption'],
  ['Vocabulaire de l’électricité','courant','pile','câble','interrupteur'],
  ['Vocabulaire de la mécanique','roue','axe','levier','ressort'],
  ['Vocabulaire de la construction','fondation','mur','charpente','toiture'],
  ['Vocabulaire de la décoration','cadre','rideau','tapis','vase'],
  ['Vocabulaire du rangement','boîte','tiroir','panier','étagère'],
  ['Vocabulaire de la lessive','linge','machine','panier','séchoir'],
  ['Vocabulaire de la couture','fil','aiguille','tissu','bouton'],
  ['Vocabulaire des achats','prix','promotion','monnaie','sac'],
  ['Vocabulaire de la poste','timbre','lettre','colis','boîte'],
  ['Vocabulaire du calendrier','date','jour','semaine','année'],
  ['Vocabulaire de l’horloge','aiguille','cadran','alarme','minute'],
  ['Vocabulaire de la concentration','attention','calme','objectif','pause'],
  ['Vocabulaire de l’énergie','force','repos','repas','mouvement'],
  ['Vocabulaire de l’équilibre','centre','appui','stabilité','bascule'],
  ['Vocabulaire de la vitesse','allure','chrono','accélération','frein'],
  ['Vocabulaire des robots','bras','capteur','roue','programme'],
  ['Vocabulaire du recyclage','tri','verre','papier','compost'],
  ['Vocabulaire de l’environnement','forêt','océan','air','sol'],
  ['Vocabulaire de la recherche','question','test','donnée','résultat'],
  ['Vocabulaire de la méthode','étape','mesure','contrôle','conclusion'],
  ['Vocabulaire de l’argumentation','thèse','exemple','raison','conclusion'],
  ['Vocabulaire de la poésie','vers','rime','strophe','image'],
  ['Vocabulaire du récit','début','nœud','dénouement','narrateur'],
  ['Vocabulaire de la magie','sort','baguette','potion','dragon'],
  ['Vocabulaire des contes','loup','princesse','ogre','forêt'],
  ['Vocabulaire de la science-fiction','robot','planète','vaisseau','laser'],
  ['Vocabulaire du policier','enquête','indice','suspect','alibi'],
  ['Vocabulaire des jouets','poupée','bille','cerf-volant','figurine'],
  ['Vocabulaire de la plage','sable','serviette','coquillage','parasol'],
  ['Vocabulaire de la piscine','bassin','bonnet','bouée','plongeon'],
  ['Vocabulaire du pique-nique','nappe','panier','sandwich','gourde'],
  ['Vocabulaire de la boulangerie','pain','farine','four','sac'],
  ['Vocabulaire du restaurant','menu','table','serveur','addition'],
  ['Vocabulaire de la table','assiette','verre','couverts','nappe'],
  ['Vocabulaire du goûter','biscuit','jus','fruit','tartine'],
  ['Vocabulaire de la pharmacie','ordonnance','comprimé','sirop','conseil'],
  ['Vocabulaire de l’hôpital','chambre','soin','blouse','patient'],
  ['Vocabulaire des urgences','appel','secours','ambulance','sirène'],
  ['Vocabulaire des articulations','genou','coude','épaule','cheville'],
  ['Vocabulaire du yoga','posture','respiration','tapis','relaxation'],
  ['Vocabulaire de la natation','nage','bassin','lunettes','plongeon'],
  ['Vocabulaire du football','but','ballon','équipe','arbitre'],
  ['Vocabulaire du tennis','raquette','filet','service','revers'],
  ['Vocabulaire du basket','panier','dribble','terrain','rebond'],
  ['Vocabulaire de la gymnastique','agrès','souplesse','équilibre','figure'],
  ['Vocabulaire du marché','étal','panier','marchand','produit'],
  ['Vocabulaire du village','place','clocher','fontaine','ruelle'],
  ['Vocabulaire du quartier','immeuble','boulangerie','parc','école'],
  ['Vocabulaire des bâtiments','mur','porte','fenêtre','toit'],
  ['Vocabulaire des rues','trottoir','panneau','feu','carrefour'],
  ['Vocabulaire des monuments','tour','pont','musée','église'],
  ['Vocabulaire des services','poste','mairie','banque','école'],
  ['Vocabulaire des continents','Europe','Afrique','Asie','Amérique'],
  ['Vocabulaire des océans','Atlantique','Pacifique','Indien','Arctique'],
  ['Vocabulaire des climats','tropical','tempéré','polaire','désertique'],
  ['Vocabulaire des roches','calcaire','basalte','grès','schiste'],
  ['Vocabulaire des ressources','eau','bois','métal','énergie'],
  ['Vocabulaire des éléments','air','eau','terre','feu'],
  ['Vocabulaire de l’astronomie','orbite','télescope','étoile','galaxie'],
  ['Vocabulaire de la physique','force','mouvement','énergie','matière'],
  ['Vocabulaire de la biologie','cellule','noyau','gène','espèce'],
  ['Vocabulaire de la géométrie','angle','droite','cercle','symétrie'],
  ['Vocabulaire des probabilités','chance','tirage','fréquence','hasard'],
  ['Vocabulaire de la matière','masse','volume','densité','poids'],
  ['Vocabulaire de la vie','naissance','croissance','reproduction','mort'],
  ['Vocabulaire de l’évolution','variation','espèce','adaptation','temps'],
  ['Vocabulaire de l’énergie renouvelable','solaire','éolien','hydraulique','thermique'],
  ['Vocabulaire de la protection de la nature','réserve','espèce','habitat','soin'],
  ['Vocabulaire de la ville','rue','place','métro','immeuble'],
  ['Vocabulaire de la campagne','champ','ferme','village','chemin'],
  ['Vocabulaire du tourisme','visite','guide','musée','monument'],
  ['Vocabulaire de l’hôtel','chambre','clé','réception','valise'],
  ['Vocabulaire de l’aéroport','enregistrement','contrôle','embarquement','vol'],
  ['Vocabulaire du train','wagon','rail','quai','conducteur'],
  ['Vocabulaire du bateau','pont','cabine','ancre','port'],
  ['Vocabulaire du vélo','pédale','guidon','selle','frein'],
  ['Vocabulaire de l’escalade','prise','corde','paroi','baudrier'],
  ['Vocabulaire du ski','piste','neige','remontée','bâton'],
  ['Vocabulaire des médias','radio','journal','écran','podcast'],
  ['Vocabulaire de l’informatique','programme','fichier','réseau','mémoire'],
  ['Vocabulaire de la programmation','code','fonction','variable','test'],
  ['Vocabulaire des données','tableau','valeur','fichier','source'],
  ['Vocabulaire de la confidentialité','choix','donnée','accord','protection'],
  ['Vocabulaire de la confiance','preuve','règle','promesse','constance'],
  ['Vocabulaire de la simplicité','clair','court','utile','direct'],
  ['Vocabulaire de l’élégance','mesure','harmonie','détail','équilibre'],
  ['Vocabulaire du parcours','départ','étape','pause','arrivée'],
  ['Vocabulaire du défi','question','choix','stratégie','victoire'],
  ['Vocabulaire de la récompense','pièce','bonus','coffre','palier'],
  ['Vocabulaire de la progression','niveau','série','record','étape'],
  ['Vocabulaire du jeu de mots','lettre','syllabe','sens','indice'],
  ['Vocabulaire des associations','groupe','famille','thème','lien'],
  ['Vocabulaire de la déduction','observation','logique','hypothèse','solution'],
  ['Vocabulaire de la variété','mélange','nuance','surprise','rotation'],
  ['Vocabulaire de la difficulté','facile','juste','subtil','expert'],
  ['Vocabulaire de la fluidité','rythme','tempo','enchaînement','pause'],
  ['Vocabulaire de la célébration','confetti','sourire','applaudissement','bravo'],
  ['Vocabulaire de l’interface','bouton','carte','menu','barre'],
  ['Vocabulaire de l’accessibilité','contraste','texte','toucher','son'],
  ['Vocabulaire de la sauvegarde','donnée','copie','restauration','version'],
  ['Vocabulaire de la migration','ancienne','nouvelle','conversion','continuité'],
  ['Vocabulaire de la mise à jour','version','correctif','nouveauté','stabilité'],
  ['Vocabulaire de la qualité','test','contrôle','fiabilité','détail'],
  ['Vocabulaire du lancement','icône','écran','accueil','partie'],
  ['Vocabulaire de la publication','fiche','capture','description','version'],
  ['Vocabulaire du hors-ligne','appareil','réseau','local','sauvegarde'],
  ['Vocabulaire du portefeuille','pièce','solde','gain','économie'],
  ['Vocabulaire de la série','enchaînement','suite','bonus','constance'],
  ['Vocabulaire du record','meilleur','chrono','score','palmarès'],
  ['Vocabulaire de l’aide','indice','thème','solution','choix'],
  ['Vocabulaire de la victoire','bravo','but','médaille','podium'],
  ['Vocabulaire de la fin','dernier','bilan','souvenir','nouveau départ'],
  ['Vocabulaire de l’avenir','extension','idée','projet','horizon'],
  ['Vocabulaire de la continuité','reprise','version','sauvegarde','progression'],
  ['Vocabulaire de la performance','temps','erreurs','record','bonus'],
  ['Vocabulaire de la précision','exactitude','détail','repère','contrôle'],
  ['Vocabulaire de la rapidité','chrono','vitesse','réflexe','temps'],
  ['Vocabulaire de la maîtrise','pratique','mémoire','vitesse','précision'],
  ['Vocabulaire de l’expérience','essai','erreur','progrès','savoir'],
  ['Vocabulaire de la patience','attente','calme','constance','persévérance'],
  ['Vocabulaire de la curiosité','question','indice','découverte','pourquoi'],
  ['Vocabulaire de la confiance','parole','secret','preuve','soutien'],
  ['Vocabulaire de l’entraide','main','conseil','écoute','soutien'],
  ['Vocabulaire du partage','idée','repas','temps','cadeau'],
  ['Vocabulaire de la famille','parent','enfant','frère','grand-parent'],
  ['Vocabulaire de la maison','porte','fenêtre','salon','cuisine'],
  ['Vocabulaire de la journée','matin','midi','soir','nuit'],
  ['Vocabulaire des saisons','hiver','printemps','été','automne'],
  ['Vocabulaire du monde vivant','forêt','océan','prairie','jardin'],
  ['Vocabulaire des ressources naturelles','eau','bois','énergie','sol'],
  ['Vocabulaire de l’environnement','air','eau','sol','forêt'],
  ['Vocabulaire de la technologie','capteur','moteur','écran','batterie'],
  ['Vocabulaire des machines','moteur','bouton','engrenage','capot'],
  ['Vocabulaire des bâtiments','fondation','mur','toit','fenêtre'],
  ['Vocabulaire de la décoration','cadre','rideau','tapis','vase'],
  ['Vocabulaire du rangement','étagère','tiroir','placard','panier'],
  ['Vocabulaire de la course','sport','vitesse','chrono','départ'],
  ['Vocabulaire de l’arrivée','destination','bilan','photo','souvenir'],
  ['Vocabulaire de l’itinéraire','départ','étape','direction','arrivée'],
  ['Vocabulaire des cartes','adresse','route','région','frontière'],
  ['Vocabulaire du territoire','frontière','région','ville','campagne'],
  ['Vocabulaire de la planète','terre','océan','continent','climat'],
  ['Vocabulaire des pays','France','Canada','Japon','Brésil'],
  ['Vocabulaire des capitales','Paris','Tokyo','Ottawa','Brasília'],
  ['Vocabulaire des langues','français','anglais','espagnol','italien'],
  ['Vocabulaire de la culture','art','langue','fête','mémoire'],
  ['Vocabulaire de la philosophie','idée','raison','vérité','question'],
  ['Vocabulaire de la justice','règle','droit','preuve','équité'],
  ['Vocabulaire de la société','famille','école','travail','loisir'],
  ['Vocabulaire du droit','contrat','règle','juge','preuve'],
  ['Vocabulaire de la carrière','métier','expérience','projet','évolution'],
  ['Vocabulaire de l’apprentissage','exercice','révision','erreur','progrès'],
  ['Vocabulaire de la formation','atelier','exercice','conseil','certificat'],
  ['Vocabulaire de la concentration','attention','silence','objectif','pause'],
  ['Vocabulaire de la détente','repos','lecture','bain','promenade'],
  ['Vocabulaire des sentiments','amour','joie','peur','colère'],
  ['Vocabulaire de la politesse','merci','bonjour','pardon','s’il vous plaît'],
  ['Vocabulaire des rencontres','bonjour','sourire','conversation','partage'],
  ['Vocabulaire de la fête','invité','cadeau','musique','gâteau'],
  ['Vocabulaire du cadeau','ruban','boîte','surprise','papier'],
  ['Vocabulaire du musée','œuvre','salle','visite','cartel'],
  ['Vocabulaire du concert','scène','public','son','rappel'],
  ['Vocabulaire du festival','stand','musique','foule','programme'],
  ['Vocabulaire du dessin','ligne','crayon','gomme','papier'],
  ['Vocabulaire de l’artisanat','outil','matière','atelier','création'],
  ['Vocabulaire des volcans','cratère','lave','cendre','éruption'],
  ['Vocabulaire des rivières','affluent','source','méandre','confluence'],
  ['Vocabulaire des lacs','rive','profondeur','eau','barque'],
  ['Vocabulaire des jardins','rosier','haie','allée','potager'],
  ['Vocabulaire des animaux sauvages','piste','empreinte','terrier','réserve'],
  ['Vocabulaire de l’énergie','solaire','éolien','hydraulique','thermique'],
  ['Vocabulaire de la recherche','question','test','donnée','résultat'],
  ['Vocabulaire de la méthode','étape','mesure','contrôle','conclusion'],
  ['Vocabulaire de la logique','preuve','règle','ordre','solution'],
  ['Vocabulaire de la comparaison','proche','différent','semblable','opposé'],
  ['Vocabulaire de la nuance','sens','contexte','détail','interprétation'],
  ['Vocabulaire de l’abstraction','idée','concept','principe','modèle'],
  ['Vocabulaire de l’évidence','clair','simple','direct','visible'],
  ['Vocabulaire de l’intuition','pressentiment','idée','choix','élan'],
  ['Vocabulaire du raisonnement','observation','comparaison','preuve','conclusion'],
  ['Vocabulaire de la stratégie','plan','ordre','priorité','décision'],
  ['Vocabulaire des nombres','zéro','douze','cent','mille'],
  ['Vocabulaire du calcul','addition','soustraction','multiplication','division'],
  ['Vocabulaire des statistiques','moyenne','total','écart','tendance'],
  ['Vocabulaire de la matière','masse','volume','densité','poids'],
  ['Vocabulaire de la vie','naissance','croissance','reproduction','mort'],
  ['Vocabulaire de l’évolution','variation','espèce','adaptation','temps'],
  ['Vocabulaire de la sécurité numérique','mot de passe','verrou','copie','confidentialité'],
  ['Vocabulaire du hors-ligne','local','appareil','donnée','continuité'],
  ['Vocabulaire de la migration','V1','V2','joueur','données'],
  ['Vocabulaire de la mise à jour','package','version','signature','compatibilité'],
  ['Vocabulaire du build','code','tests','bundle','APK'],
  ['Vocabulaire de la publication','AAB','fiche','captures','description'],
  ['Vocabulaire de l’application','écran','icône','bouton','réglages'],
  ['Vocabulaire du téléphone','écran','batterie','sonnerie','chargeur'],
  ['Vocabulaire des réglages','son','vibration','langue','affichage'],
  ['Vocabulaire de l’accessibilité','contraste','taille','son','toucher'],
  ['Vocabulaire du corpus','mot','famille','niveau','validation'],
  ['Vocabulaire du validateur','doublon','quantité','distance','rapport'],
  ['Vocabulaire des chapitres','vingt-cinq','thème','progression','palier'],
  ['Vocabulaire des paliers','cinq','dix','vingt-cinq','cent'],
  ['Vocabulaire des séries','suite','enchaînement','record','bonus'],
  ['Vocabulaire des récompenses','pièce','coffre','badge','bonus'],
  ['Vocabulaire du niveau final','cinq cents','final','sommet','bilan'],
  ['Vocabulaire de la suite','rejouer','partager','progresser','attendre'],
  ['Vocabulaire du futur','extension','nouveau','projet','horizon'],
  ['Vocabulaire de la fin','bilan','fierté','accomplissement','avenir'],
  ['Vocabulaire de la victoire','sixième','famille','bravo','progression'],
  ['Vocabulaire de la solution','réponse','validation','suite','victoire'],
  ['Vocabulaire de l’animation','mouvement','haptique','message','confetti'],
  ['Vocabulaire de l’erreur','shake','désélection','correction','suite'],
  ['Vocabulaire du portefeuille','solde','gain','coût','choix'],
  ['Vocabulaire de l’économie','base','difficulté','précision','rapidité'],
  ['Vocabulaire de la performance','temps','erreurs','série','parfait'],
  ['Vocabulaire de la qualité','tests','rapport','validation','stabilité'],
  ['Vocabulaire de la continuité','sauvegarde','migration','hors-ligne','reprise'],
  ['Vocabulaire de la publication','Play Console','version','package','signature'],
  ['Vocabulaire de la version','2.0.0','versionCode','release','bundle'],
  ['Vocabulaire de la livraison','AAB','APK','rapport','chemin'],
  ['Vocabulaire du package','com.vincentcosti.motsencascade','Android','mise à jour','V2'],
  ['Vocabulaire de la signature','clé','certificat','SHA-256','compatibilité'],
  ['Vocabulaire du rapport','résumé','tests','diff','commit'],
  ['Vocabulaire de la branche','main','feature/V2','PR','release'],
  ['Vocabulaire des amis','téléchargement','installation','partage','jeu'],
  ['Vocabulaire du résultat final','complet','stable','jouable','prêt'],
];

const variants = ['Essentiels', 'Repères', 'Collection', 'Atelier'];
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();

export const FAMILY_LIBRARY: Family[] = SEEDS.flatMap((seed, index) => variants.map((variant, variantIndex) => ({
  id: 'family-' + index + '-' + variantIndex,
  label: seed[0] + ' · ' + variant,
  groupKey: normalize(seed[0]).replace(/\s+/g, '-'),
  words: seed.slice(1).map(word => word.trim()),
})));

function hash(value: string): number {
  let result = 2166136261;
  for (const character of value) result = Math.imul(result ^ character.charCodeAt(0), 16777619);
  return result >>> 0;
}

function shuffled<T>(values: T[], seed: number): T[] {
  const result = [...values];
  for (let i = result.length - 1; i > 0; i -= 1) {
    const index = hash(String(seed) + ':' + String(i)) % (i + 1);
    [result[i], result[index]] = [result[index], result[i]];
  }
  return result;
}

function levelFingerprint(level: Level): string {
  return level.families.map((family) => `${normalize(family.label)}:${family.words.map(normalize).sort().join(',')}`).sort().join('|');
}

function buildLevel(levelId: number, usedGroups: string[], usedWords: string[], salt = 0): Level {
  const families: Family[] = [];
  const words = new Set<string>();
  const start = (levelId * 37 + Math.floor(levelId / 20) * 11 + salt * 53) % FAMILY_LIBRARY.length;
  let cursor = start;
  while (families.length < 6 && cursor < start + FAMILY_LIBRARY.length * 2) {
    const candidate = FAMILY_LIBRARY[cursor % FAMILY_LIBRARY.length];
    const recent = usedGroups.slice(-120).includes(candidate.groupKey);
    const sameInLevel = families.some(family => family.groupKey === candidate.groupKey);
    const collides = candidate.words.some(word => words.has(normalize(word)));
    const repeatedRecently = candidate.words.some(word => usedWords.includes(normalize(word)));
    if (!recent && !sameInLevel && !collides && !repeatedRecently) {
      families.push(candidate);
      candidate.words.forEach(word => words.add(normalize(word)));
    }
    cursor += 1;
  }
  for (const candidate of FAMILY_LIBRARY) {
    if (families.length >= 6) break;
    if (families.some(family => family.id === candidate.id)) continue;
    families.push(candidate);
  }
  return {
    id: levelId,
    chapter: Math.ceil(levelId / 20),
    difficulty: difficultyForLevel(levelId),
    families,
    words: shuffled(families.flatMap(family => family.words), hash('level-' + levelId)),
  };
}

const levels: Level[] = [];
const recentGroups: string[] = [];
const recentWords: string[] = [];
const fingerprints = new Set<string>();
for (let levelId = 1; levelId <= 500; levelId += 1) {
  let salt = 0;
  let level = buildLevel(levelId, recentGroups, recentWords, salt);
  while (fingerprints.has(levelFingerprint(level)) && salt < 40) {
    salt += 1;
    level = buildLevel(levelId, recentGroups, recentWords, salt);
  }
  fingerprints.add(levelFingerprint(level));
  levels.push(level);
  level.families.forEach(family => recentGroups.push(family.groupKey));
  level.words.forEach(word => recentWords.push(normalize(word)));
  while (recentWords.length > 480) recentWords.shift();
}

export const LEVELS = levels;
export const TOTAL_LEVELS = LEVELS.length;
export const FAMILIES_PER_LEVEL = 6;
export const WORDS_PER_FAMILY = 4;
export function getLevel(levelId: number): Level | undefined { return LEVELS[levelId - 1]; }
export function familyForWord(level: Level, word: string): Family | undefined {
  const target = normalize(word);
  return level.families.find(family => family.words.some(item => normalize(item) === target));
}
